/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
int main(void)
{   
    RCC->AHB1ENR |= (1 << 0); // Enciende el reloj de GPIOA (bit 0)
    GPIOA->MODER &= ~(0b11 << (5 * 2)); // Limpia bits 11:10
    GPIOA->MODER |= (0b01 << (5 * 2)); // Modo salida
    GPIOA->OTYPER &= ~(1 << 5); // Push-Pull
    GPIOA->OSPEEDR &= ~(0b11 << (5 * 2)); // Baja velocidad
    GPIOA->PUPDR &= ~(0b11 << (5 * 2)); // Sin resistencias internas
    GPIOA->ODR |= (0 << 5); // PA5 = 1 → 3.3V → LED encendido
	while(1)
    {
        
    }
}
