/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

int main(void)
{   
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // Enable TIM3 clock
    TIM3->CR1 &= ~TIM_CR1_CEN; // Disable TIM3 COUNTER
    /*
    CEN IS OFF FIRST TO PREVENT THE COUNTER FROM STARTING TO COUNT BEFORE WE SET THE PRESCALER AND AUTO-RELOAD VALUE.
    LATTER WE WILL ENABLE THE COUNTER AFTER WE SET THE PRESCALER AND AUTO-RELOAD VALUE. TO AVOID PROBLEMS
    */
    TIM3->CR1 |= TIM_CR1_ARPE; // Enable TIM3 COUNTER
    TIM3->PSC = 16000 - 1; // Set prescaler to 16000 for 1ms tick (assuming 16MHz clock)
    TIM3->ARR = 500 - 1; // Set auto-reload value for 500 ticks equivalent to 499 events
    TIM3->EGR |= TIM_EGR_UG; // Generate an update event to load the prescaler value 
    /* 
    THIS UPLOAD THE REAL Value OF AAR AND PSC INTO THE COUNTER AND THE PRESCALER.
    OTHERWISE, THE COUNTER WILL NOT START COUNTING UNTIL THE NEXT UPDATE EVENT OCCURS.
    REMEMBER WE ENABLES THE ARPE BIT, SO THE COUNTER WILL NOT UPDATE THE ARR VALUE UNTIL
    THE NEXT UPDATE EVENT OCCURS.
    */
    /*
    NOW WE GONNA CLEAR THE UIF REGISTER THAT IS THE FLAG THAT INDICATES AN UPDATE EVENT HAS OCCURRED.
    WE NEED TO CLEAR IT BECAUSE WE WANT TO START COUNTING FROM 0, AND WE DON'T WANT TO HAVE AN UPDATE EVENT OCCURRING IMMEDIATELY AFTER WE ENABLE
    THIS MIGHT BE CAUSED WHEN WE USED DE UG TO UPDATE OUT ARPE AND PSC VALUES.
    */
   TIM3->SR &= ~TIM_SR_UIF; // Clear the update interrupt flag
   TIM3->DIER |= TIM_DIER_UIE; // Enable TIM3 update interrupt
   /*
   FROM THE TEACHER'S DIAGRAM, WE NEED TO ENABLE THE UIE BIT WICH IS AN AND GATE THAT CONTROLS THE UPDATE
   OF THE INTERUPT FLAG. WHEN THE UIF FLAG IS SET, IT WILL GENERATE AN INTERRUPT IF THE UIE BIT IS ALSO SET.
   */
  NVIC_EnableIRQ(TIM3_IRQn);    
  /*
    WE ALLOWING THE CPU TO RECEIVE INTERRUPTS FROM THE TIM3 PERIPHERAL. 
    WE NEED TO ENABLE THE NVIC INTERRUPT FOR TIM3.
  */

    while (1)
    {
        // Main loop
    }
}
